export const FeatureKeys = {
  ENABLE_RECEPTION_MODULE: 'ENABLE_RECEPTION_MODULE',
  ENABLE_DOCTOR_MODULE: 'ENABLE_DOCTOR_MODULE',
  ENABLE_VITAL_MODULE: 'ENABLE_VITAL_MODULE',
  ENABLE_LAB_MODULE: 'ENABLE_LAB_MODULE',
  ENABLE_PHARMACY_MODULE: 'ENABLE_PHARMACY_MODULE',
} as const;

export type FeatureKey = (typeof FeatureKeys)[keyof typeof FeatureKeys];
